<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mk Makefile makefile</string>
	</array>
	<key>name</key>
	<string>Makefile-Simple</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>\#.*$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Conditions</string>
			<key>match</key>
			<string>^\s*(else\s+)?(ifeq|ifneq|ifdef|ifndef|if)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Conditions</string>
			<key>match</key>
			<string>^\s*(else|endif)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variable affectation</string>
			<key>match</key>
			<string>^\s*([^?:+!$()#]+)\s*((\?|:|::|\+|!)?\=)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Functions</string>
			<key>match</key>
			<string>\$\((subst|patsubst|strip|findstring|filter|filter-out|sort|word|wordlist|words|firstword|lastword|dir|notdir|suffix|basename|addsuffix|addprefix|join|wildcard|realpath|abspath|if|or|and|foreach|file|call|value|eval|origin|flavor|error|warning|info|guile|shell)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Rule</string>
			<key>match</key>
			<string>^\ *[^\$\(\t\#]+?\s*:\s*</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Target</string>
			<key>match</key>
			<string>^\ *(\$\()(.+?)(\)[^:\t ]*\s*:)\s*</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Includes</string>
			<key>match</key>
			<string>^\s*\-?\s*include</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variable</string>
			<key>match</key>
			<string>\$\(([^\):]+)(:[.*?]=[.*?])?\)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.Makefile-Simple</string>
	<key>uuid</key>
	<string>30c797d2-0b7c-4348-be6b-1d08fbcc1e9b</string>
</dict>
</plist>
